#!/bin/bash


# We still need this.
windows() { [[ -n "$WINDIR" ]]; }


# Cross-platform symlink function. With one parameter, it will check
# whether the parameter is a symlink. With two parameters, it will create
# a symlink to a file or directory, with syntax: link $linkname $target
ext-link() {
    if [[ -z "$2" ]]; then
        # Link-checking mode.
        if windows; then
            fsutil reparsepoint query "$1" > /dev/null
        else
            [[ -h "$1" ]]
        fi
    else
        # Link-creation mode.
        if windows; then
			if [[ ${2:0:1} == "." ]]; then
				temp=$(pwd)/${2}
			else
				temp=$2
			fi
			if [[ ${temp:1:1} != ":" ]]; then
				temp=${temp:1:1}:${temp:2}
			fi
			target=${temp//\//\\}
            # Windows needs to be told if it's a directory or not. Infer that.
            # Also: note that we convert `/` to `\`. In this case it's necessary.
            if [[ -d "$2" ]]; then
				cmd <<< "mklink /D \"$1\" \"$target\"" > /dev/null
            else
				cmd <<< "mklink \"$1\" \"$target\"" > /dev/null
            fi
        else
            # You know what? I think ln's parameters are backwards.
            ln -s "$2" "$1"
        fi
    fi
}


# Remove a link, cross-platform.
ext-rmlink() {
    if windows; then
        # Again, Windows needs to be told if it's a file or directory.
        if [[ -d '$1' ]]; then
            rmdir '$1'
        else
            rm '$1'
        fi
    else
        rm '$1'
    fi
}


# Toggle directory between UHOME[/u/u~u/a0a/] and HOME[/i/a0a/]
ext-cd() {
	temp=$(pwd)
	if [[ ${temp:1:1} == 'u' ]]; then
		cd $SHOME/./
		if [[ $1 != $HOME ]]; then
			cd ./${temp:11}
		fi
	elif [[ ${temp:3:3} == 'a0a' ]]; then
		cd $HOME/../
		if [[ $1 != $HOME ]]; then
			cd ./${temp:7}
		fi
	fi
}


ext-vbox() {
	cmd <<< "\"$VBOX_MSI_INSTALL_PATH\VirtualBox.exe\"" > /dev/null & 
}
