#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Author: ileler@qq.com

import os
import sys
import json

PATH = sys.argv[1] if len(sys.argv) > 1 else '.'
if not os.path.isdir(PATH):
    print('invalid path')
    sys.exit()

def title(file):
    with open(file, 'r') as f:
        return f.readline()[1:].strip()

def walk(dir):
    for root, dirs, files, in os.walk(dir):
        indexFile = os.path.join(root, '0.index')
        index = json.load(open(indexFile)) if os.path.exists(indexFile) else {}

        for d in dirs:
            index[d] = d;
            #walk(os.path.join(dir, d))
        for f in files:
            if (f != '0.index' and f != 'index.md'):
                index[f] = title(os.path.join(root, f))

        for k in list(index):
            if not os.path.exists(os.path.join(root, k)):
                print('delete invalid index [%s -> %s]' % (root, k))
                del index[k]

        if not os.path.exists(os.path.join(root, 'index.md')):
            print('[%s] directory is missing [index.md]' % root)

        with open(indexFile, 'w') as wf:
            json.dump(index, wf, indent = 4)

walk(PATH)
