#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Author: ileler@qq.com

import os
import sys
import json

PATH = sys.argv[1] if len(sys.argv) > 1 else '.'
if not os.path.isdir(PATH):
    print('invalid path')
    sys.exit()

def walk(dir):
    for root, dirs, files, in os.walk(dir):
        index = {}

        for d in dirs:
            index[d] = d;
            #walk(os.path.join(dir, d))
        for f in files:
            if (f != '0.index' and f != 'index.md'):
                index[f] = f;

        if not os.path.exists(os.path.join(root, 'index.md')):
            print('[%s] directory is missing [index.md]' % root)
        with open(os.path.join(root, '0.index'), 'w') as f:
            json.dump(index, f)

walk(PATH)
